version: "3.9"

services:
    php:
        container_name: php_elmy
        build:
            context: .
            dockerfile: .docker/php/Dockerfile
        ports:
            - '9002:9000'
        user: "www-data"
        working_dir: /var/www/elmy
        stdin_open: true
        tty: true
        volumes:
            - .:/var/www/elmy

    nginx:
        container_name: 'nginx_elmy'
        image: nginx:stable-alpine
        ports:
            - '8080:80'
        volumes:
            - .:/var/www/elmy
            - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
        working_dir: /var/www
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        depends_on:
            - php

